<x-app-layout>
<div class="space-y-5">
    <div><p class="text-sm text-black/45">Monitoring</p><h2 class="mt-1 text-2xl font-semibold">Monitoring Pembelian</h2><p class="mt-1 text-sm text-black/40">Pantau transaksi pembelian dan status pengadaan secara real-time dari data transaksi.</p></div>
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-black/45">Transaksi Hari Ini</p><p class="mt-2 text-2xl font-semibold">{{ $todayTransactions }}</p></div>
        <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-black/45">Nilai Pembelian Hari Ini</p><p class="mt-2 text-2xl font-semibold">Rp {{ number_format($todayPurchases,0,',','.') }}</p></div>
        <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-black/45">Draft Menunggu</p><p class="mt-2 text-2xl font-semibold">{{ $pending }}</p></div>
    </div>
    <form method="GET" class="flex gap-3 rounded-2xl border bg-white p-5"><input name="search" value="{{ $search }}" placeholder="Cari invoice pembelian..." class="w-full rounded-xl border px-3 py-2.5"><button class="rounded-xl bg-[#171719] px-5 py-2.5 font-semibold text-white">Cari</button></form>
    <div class="overflow-hidden rounded-2xl border bg-white"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b text-xs uppercase text-black/45"><tr><th class="px-5 py-4">Invoice</th><th class="px-5 py-4">Tanggal</th><th class="px-5 py-4">Supplier</th><th class="px-5 py-4">Item</th><th class="px-5 py-4">Status</th><th class="px-5 py-4 text-right">Total</th></tr></thead><tbody class="divide-y">@forelse($purchases as $purchase)<tr><td class="px-5 py-4 font-medium">{{ $purchase->invoice }}</td><td class="px-5 py-4">{{ $purchase->purchase_date->format('d/m/Y') }}</td><td class="px-5 py-4">{{ $purchase->supplier->name }}</td><td class="px-5 py-4">{{ $purchase->items_count }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-medium @if($purchase->status === 'received') bg-green-50 text-green-700 @elseif($purchase->status === 'cancelled') bg-red-50 text-red-600 @else bg-yellow-50 text-yellow-700 @endif">{{ ucfirst($purchase->status) }}</span></td><td class="px-5 py-4 text-right font-semibold">Rp {{ number_format((float)$purchase->total,0,',','.') }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-black/40">Belum ada transaksi pembelian.</td></tr>@endforelse</tbody></table></div>@if($purchases->hasPages())<div class="border-t px-5 py-4">{{ $purchases->links() }}</div>@endif</div>
</div>
</x-app-layout>