<x-app-layout>
<div x-data="{items:[{product_id:'',quantity:1,unit_price:0}]}" class="mx-auto max-w-5xl space-y-5">
    <div><p class="text-xs font-semibold uppercase tracking-wide text-black/40">Transaksi</p><h1 class="mt-1 text-2xl font-bold">Pembelian Baru</h1><p class="mt-1 text-sm text-black/50">{{ auth()->user()->role === 'purchasing' ? 'Buat purchase order sebagai draft tanpa mengubah stok.' : 'Transaksi langsung berstatus diterima dan otomatis menambah stok.' }}</p></div>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route($purchaseRoutePrefix.'.store') }}" class="space-y-5 rounded-2xl border border-black/5 bg-white p-6 shadow-sm">@csrf
        <div class="grid gap-4 md:grid-cols-3"><div><label class="text-sm font-semibold">Invoice</label><input name="invoice" value="{{ old('invoice') }}" class="mt-2 w-full rounded-xl border-black/10" required></div><div><label class="text-sm font-semibold">Supplier</label><select name="supplier_id" class="mt-2 w-full rounded-xl border-black/10" required><option value="">Pilih supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected(old('supplier_id')==$supplier->id)>{{ $supplier->name }}</option>@endforeach</select></div><div><label class="text-sm font-semibold">Tanggal</label><input type="date" name="purchase_date" value="{{ old('purchase_date',now()->toDateString()) }}" class="mt-2 w-full rounded-xl border-black/10" required></div></div>
        <div><div class="mb-3 flex items-center justify-between"><h2 class="font-semibold">Item Pembelian</h2><button type="button" @click="items.push({product_id:'',quantity:1,unit_price:0})" class="rounded-lg border border-black/10 px-3 py-1.5 text-xs font-semibold">+ Item</button></div>
            <div class="space-y-3"><template x-for="(item,index) in items" :key="index"><div class="grid gap-3 md:grid-cols-[1fr_130px_180px_40px]"><select :name="'items['+index+'][product_id]'" x-model="item.product_id" class="rounded-xl border-black/10" required><option value="">Pilih produk</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->sku }} - {{ $product->name }}</option>@endforeach</select><input type="number" min="1" :name="'items['+index+'][quantity]'" x-model="item.quantity" class="rounded-xl border-black/10" required><input type="number" min="0" step="0.01" :name="'items['+index+'][unit_price]'" x-model="item.unit_price" class="rounded-xl border-black/10" required><button type="button" @click="items.length>1 && items.splice(index,1)" class="rounded-xl border border-red-200 text-red-600">×</button></div></template></div>
        </div>
        <div><label class="text-sm font-semibold">Catatan</label><textarea name="notes" rows="3" class="mt-2 w-full rounded-xl border-black/10">{{ old('notes') }}</textarea></div>
        <div class="flex justify-end gap-2"><a href="{{ route($purchaseRoutePrefix.'.index') }}" class="rounded-xl border border-black/10 px-4 py-2.5 text-sm font-semibold">Batal</a><button class="rounded-xl bg-[#171719] px-4 py-2.5 text-sm font-semibold text-white">{{ auth()->user()->role === 'purchasing' ? 'Simpan Draft PO' : 'Simpan Pembelian' }}</button></div>
    </form>
</div>
</x-app-layout>