<x-app-layout>
<div class="space-y-5">
    <div><p class="text-sm text-black/45 dark:text-white/45">Report</p><h2 class="mt-1 text-2xl font-semibold">Laporan Stok</h2></div>
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-4">
        <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-black/45">Produk</p><p class="mt-2 text-2xl font-semibold">{{ $totalProducts }}</p></div>
        <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-black/45">Total Stok</p><p class="mt-2 text-2xl font-semibold">{{ number_format($totalStock,0,',','.') }}</p></div>
        <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-black/45">Stok Rendah</p><p class="mt-2 text-2xl font-semibold">{{ $lowStock }}</p></div>
        <div class="rounded-2xl border bg-white p-5"><p class="text-sm text-black/45">Habis</p><p class="mt-2 text-2xl font-semibold">{{ $outOfStock }}</p></div>
    </div>
    <form method="GET" class="flex gap-3 rounded-2xl border bg-white p-5"><input name="search" value="{{ $search }}" placeholder="Cari nama atau SKU..." class="w-full rounded-xl border px-3 py-2.5"><button class="rounded-xl bg-[#171719] px-5 py-2.5 font-semibold text-white">Cari</button></form>
    <div class="overflow-hidden rounded-2xl border bg-white"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b text-xs uppercase text-black/45"><tr><th class="px-5 py-4">SKU</th><th class="px-5 py-4">Produk</th><th class="px-5 py-4">Kategori</th><th class="px-5 py-4 text-right">Stok</th><th class="px-5 py-4">Status</th></tr></thead><tbody class="divide-y">@forelse($products as $product)<tr><td class="px-5 py-4">{{ $product->sku }}</td><td class="px-5 py-4 font-medium">{{ $product->name }}</td><td class="px-5 py-4">{{ $product->category->name }}</td><td class="px-5 py-4 text-right font-semibold">{{ number_format($product->stock,0,',','.') }}</td><td class="px-5 py-4">@if($product->stock===0)<span class="rounded-full bg-red-50 px-2.5 py-1 text-xs font-medium text-red-600">Habis</span>@elseif($product->stock<=5)<span class="rounded-full bg-yellow-50 px-2.5 py-1 text-xs font-medium text-yellow-700">Rendah</span>@else<span class="rounded-full bg-green-50 px-2.5 py-1 text-xs font-medium text-green-700">Aman</span>@endif</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-black/40">Tidak ada produk.</td></tr>@endforelse</tbody></table></div>@if($products->hasPages())<div class="border-t px-5 py-4">{{ $products->links() }}</div>@endif</div>
</div>
</x-app-layout>