<div class="grid gap-5">
<div><label class="text-sm font-semibold dark:text-white">Nama</label><input name="name" value="{{ old('name',$user->name ?? '') }}" class="mt-2 w-full rounded-xl border-black/10 dark:border-white/10 dark:bg-white/[0.04] dark:text-white" required></div>
<div><label class="text-sm font-semibold dark:text-white">Email</label><input type="email" name="email" value="{{ old('email',$user->email ?? '') }}" class="mt-2 w-full rounded-xl border-black/10 dark:border-white/10 dark:bg-white/[0.04] dark:text-white" required></div>
<div><label class="text-sm font-semibold dark:text-white">Role</label><select name="role" class="mt-2 w-full rounded-xl border-black/10 dark:border-white/10 dark:bg-white/[0.04] dark:text-white" required>@foreach(['admin','super-admin','gudang','kasir','purchasing','kurir','customer'] as $role)<option value="{{ $role }}" @selected(old('role',$user->role ?? '') === $role)>{{ $role }}</option>@endforeach</select></div>
@if(isset($user))
<div class="rounded-xl bg-black/[0.025] p-4 dark:bg-white/[0.04]"><label class="flex items-center gap-3 text-sm font-semibold dark:text-white"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$user->is_active))> Akun aktif</label><p class="mt-1 text-xs text-black/40 dark:text-white/40">Akun nonaktif tidak dapat login.</p></div>
@endif
<div><label class="text-sm font-semibold dark:text-white">Password {{ isset($user) ? '(opsional)' : '' }}</label><input type="password" name="password" class="mt-2 w-full rounded-xl border-black/10 dark:border-white/10 dark:bg-white/[0.04] dark:text-white" {{ isset($user) ? '' : 'required' }}><p class="mt-1 text-xs text-black/40 dark:text-white/40">Minimal 8 karakter.</p></div>
<div><label class="text-sm font-semibold dark:text-white">Konfirmasi Password</label><input type="password" name="password_confirmation" class="mt-2 w-full rounded-xl border-black/10 dark:border-white/10 dark:bg-white/[0.04] dark:text-white"></div>
</div>
<div class="mt-6 flex justify-end gap-2"><a href="{{ route('admin.users.index') }}" class="rounded-xl border border-black/10 px-4 py-2.5 text-sm font-semibold dark:border-white/10 dark:text-white">Batal</a><button class="rounded-xl bg-[#A8F23A] px-4 py-2.5 text-sm font-semibold text-black">Simpan</button></div>